import Head from 'next/head';
import type { NextPage } from 'next';
import Link from 'next/link';
import { Box, Container, Grid, Text, Button } from '@chakra-ui/react';
import { useState, useEffect, useContext } from 'react';
import { useRouter } from 'next/router';
import axios from 'axios';

import { AuthContext } from 'providers/AuthContext';

const Login: NextPage = () => {
  const AUTH_URL = `https://accounts.spotify.com/authorize?response_type=code&client_id=${process.env.NEXT_PUBLIC_SPOTIFY_CLIENT_ID}&response_type=code&redirect_uri=${process.env.NEXT_PUBLIC_BASE_URL}/login&scope=user-read-private%20user-top-read%20playlist-read-private%20playlist-read-collaborative%20user-read-recently-played%20user-follow-read&state=hello`;

  const router = useRouter();

  // @ts-ignore
  const { authenticated, setauthenticated } = useContext(AuthContext);
  const [authenticating, setAuthenticating] = useState(false);

  useEffect(() => {
    document.body.style.backgroundColor = 'white';

    if (authenticated) {
      console.log('authenticated from login');
      router.push('/');
      return;
    }

    if (router.query.code) {
      // console.log('code from spotify: ', router.query.code);
      setAuthenticating(true);

      axios
        .post(`/api/login`, {
          code: router.query.code,
        })
        .then((res) => {
          const token_data = { ...res.data, timestamp: Date.now() };
          window.localStorage.setItem('access_token', JSON.stringify(token_data));
          setauthenticated(true);
          router.push('/');
        })
        .catch((err) => {
          setAuthenticating(false);
          console.error(err);
        });
      return;
    }
  });

  return (
    <>
      <Head>
        <title>Spotify Profile</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
        {/* <link rel="icon" href="/logo/spotify-logo-png-7053.png" /> */}
      </Head>
      <Box
        as="main"
        display={'flex'}
        flexDir={'column'}
        placeContent="center"
        h={'100vh'}
        w={'100vw'}
      >
        <Text mx={'auto'}>Spotify Profile</Text>
        <Link href={AUTH_URL}>
          {/* <Button
            mx={'auto'}
            onClick={() => {
              router.push('.');
            }}
          >
            Login
          </Button> */}
          {/*TODO - Make the button become a loading spinner when authenticating*/}
          <Button mx={'auto'}>Login</Button>
        </Link>
      </Box>
    </>
  );
};

export default Login;
