import Head from 'next/head';
import type { NextPage } from 'next';
import Link from 'next/link';
import { Box, Button, Image, Text } from '@chakra-ui/react';
import { useState, useEffect, useContext } from 'react';
import { useRouter } from 'next/router';
import axios from 'axios';

import { AuthContext } from 'providers/AuthContext';

const Login: NextPage = () => {
  const AUTH_URL = `https://accounts.spotify.com/authorize?response_type=code&client_id=${process.env.NEXT_PUBLIC_SPOTIFY_CLIENT_ID}&response_type=code&redirect_uri=${process.env.NEXT_PUBLIC_BASE_URL}/login&scope=user-read-private%20user-top-read%20playlist-read-private%20playlist-read-collaborative%20user-read-recently-played%20playlist-modify-public%20playlist-modify-private%20user-follow-read&state=hi`;

  const router = useRouter();

  // @ts-ignore
  const { authenticated, setauthenticated } = useContext(AuthContext);
  const [authenticating, setAuthenticating] = useState(false);

  useEffect(() => {
    document.body.style.backgroundColor = 'rgb(24,24,24)';
    if (authenticated) {
      console.log('authenticated from login');
      router.push('/');
      return;
    }

    if (router.query.code) {
      // console.log('code from spotify: ', router.query.code);
      setAuthenticating(true);

      axios
        .post(`/api/login`, {
          code: router.query.code,
        })
        .then((res) => {
          const token_data = { ...res.data, timestamp: Date.now() };
          window.localStorage.setItem(
            'access_token',
            JSON.stringify(token_data)
          );
          setauthenticated(true);
          router.push('/');
        })
        .catch((err) => {
          setAuthenticating(false);
          console.error(err);
        });
      return;
    }
  });

  return (
    <>
      <Head>
        <title>Spotify Profile</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <link
          rel="icon"
          href="/spotify-logo.ico"
        />
      </Head>
      <Box
        as="main"
        display={'flex'}
        flexDir={'column'}
        alignItems={'center'}
        justifyContent={'center'}
        color="white"
        h="100vh"
      >
        <Image
          src="/logo/spotify-logo-png-7053.png"
          alt="Spotify Logo"
          w="10rem"
          cursor={'pointer'}
        />
        <Text
          mt="1.2rem"
          fontSize={'2rem'}
          fontWeight={'extrabold'}
          textAlign={'center'}
        >
          Spotify Profile
        </Text>
        <Link
          href={AUTH_URL}
          passHref
        >
          <Text
            as="a"
            display={'inline-block'}
            mt="1.8rem"
            color={'white'}
            bgColor={'brand.spotifyGreen'}
            _hover={{ filter: 'brightness(110%)' }}
            _active={{ filter: 'brightness(110%)' }}
            borderRadius="full"
            transition="all 0.2s ease-in-out"
            p="1rem 3rem"
            fontWeight={'bold'}
            fontSize="1.2rem"
            letterSpacing={'widest'}
            whiteSpace={'normal'}
            textAlign={'center'}
          >
            LOGIN TO SPOTIFY
          </Text>
        </Link>
      </Box>
    </>
  );
};

export default Login;
