import Head from 'next/head';
import type { NextPage } from 'next';
import Link from 'next/link';
import { Box, Container, Grid, Text, Button } from '@chakra-ui/react';
import { useState, useEffect, useContext } from 'react';
import { useRouter } from 'next/router';
import axios from 'axios';

import { AuthContext } from 'providers/AuthContext';

const Login: NextPage = () => {
  const AUTH_URL = `https://accounts.spotify.com/authorize?response_type=code&client_id=0b655a2196a541f4a00f7467e8496d0a&response_type=code&redirect_uri=http://localhost:3000/login&scope=user-read-private%20user-top-read%20playlist-read-private%20playlist-read-collaborative%20user-read-recently-played&state=hello`;

  const router = useRouter();

  // @ts-ignore
  const { authenticated, setauthenticated } = useContext(AuthContext);
  const [authenticating, setAuthenticating] = useState(false);

  useEffect(() => {
    console.log('useEffect from Login');
    if (authenticated) {
      console.log('authenticated from login');
      router.push('/');
      return;
    }

    if (router.query.code) {
      console.log('code from spotify: ', router.query.code);
      setAuthenticating(true);

      axios
        .post(`/api/login`, {
          code: router.query.code,
        })
        .then((res) => {
          console.log('successful login: ', res);
          window.localStorage.setItem('access_token', JSON.stringify(res.data));
          setauthenticated(true);
          router.push('/');
        })
        .catch((err) => {
          setAuthenticating(false);
          console.error(err);
        });
      return;
    }
  });

  return (
    <>
      <Head>
        <title>Spotify Profile</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
        {/* <link rel="icon" href="/logo/spotify-logo-png-7053.png" /> */}
      </Head>
      <Box
        as="main"
        display={'flex'}
        flexDir={'column'}
        placeContent="center"
        h={'100vh'}
        w={'100vw'}
      >
        <Text mx={'auto'}>Spotify Profile</Text>
        <Link href={AUTH_URL}>
          {/* <Button
            mx={'auto'}
            onClick={() => {
              router.push('.');
            }}
          >
            Login
          </Button> */}
          <Button mx={'auto'}>Login</Button>
        </Link>
      </Box>
    </>
  );
};

export default Login;
