import Head from 'next/head';
import type { NextPage } from 'next';
import { Box, Container, Grid, Text, Button } from '@chakra-ui/react';
import { useState, useEffect, useContext } from 'react';

import { AuthContext } from 'providers/AuthContext';
import Counter from 'components/Counter';

const Login: NextPage = () => {
  // @ts-ignore
  const { count, setcount } = useContext(AuthContext);

  useEffect(() => {
    console.log('useEffect from test');
  });

  return (
    <>
      <Head>
        <title>Spotify Profile</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
        {/* <link rel="icon" href="/logo/spotify-logo-png-7053.png" /> */}
      </Head>
      <Box
        as="main"
        display={'flex'}
        flexDir={'column'}
        placeContent="center"
        h={'100vh'}
        w={'100vw'}
      >
        <Text mx={'auto'}>{count}</Text>

        <Button
          onClick={() => setcount(count+1)}
          mx={'auto'}
        >
          +1
        </Button>
        <Counter />
      </Box>
    </>
  );
};

export default Login;
