import Head from 'next/head';
import { Box, Text, Button } from '@chakra-ui/react';
import { useEffect, useState, useContext } from 'react';

import { AuthContext } from 'providers/AuthContext';
import NavBar from 'components/NavBar';
import Link from 'next/link';

type Props = {
  children?: React.ReactNode;
};

function Layout({ children }: Props) {
  // @ts-ignore
  const { authenticated, setauthenticated, loading, setLoading } =
    useContext(AuthContext);

  useEffect(() => {
    console.log('useEffect from Layout');
    if (authenticated && window.localStorage.getItem('access_token')) {
      setLoading(false);
    }
  });

  return (
    <>
      <Head>
        <title>Spotify Profile</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
        {/* <link rel="icon" href="/logo/spotify-logo-png-7053.png" /> */}
      </Head>

      {
        <>
          <NavBar />
          {!loading ? (
            <>{children}</>
          ) : (
            <>
              <Box
                as="main"
                display={'flex'}
                flexDir={'column'}
                placeContent="center"
                h={'100vh'}
                w={'100vw'}
              >
                <Text mx={'auto'}>Loading</Text>
              </Box>
            </>
          )}
        </>
      }
    </>
  );
}

export default Layout;
